name: Deploy Main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Deploy to server (main)
        run: |
          ssh -o StrictHostKeyChecking=no azureuser@${{ secrets.SERVER_IP }} << 'EOF'
            cd /var/www/libraryapp/LibraryManagement
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            python manage.py migrate
            sudo systemctl restart libraryapp
          EOF